[package]
name = "aptos-lc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
blst = "0.3.11"
getset = "0.1.2"
proptest = "1.4.0"
thiserror = "1.0.56"
bcs = { git = "https://github.com/aptos-labs/bcs.git", rev = "d31fab9d81748e2594be5cd5cdf845786a30562d" } 
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
serde = "1.0.195"
serde_bytes = "0.11.14"

