[package]
name = "aptos-lc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
blst = "0.3.11"
bytes = { version = "1.5.0", features = ["serde"] }
getset = "0.1.2"
hex = "0.4.3"
proptest = "1.4.0"
test-strategy = "0.3.1"
thiserror = "1.0.56"
bcs = { git = "https://github.com/aptos-labs/bcs.git", rev = "d31fab9d81748e2594be5cd5cdf845786a30562d" }
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
serde = "=1.0.152"
serde_bytes = "0.11.6"
serde_json = "1"

# shallow cloning would sure help here https://github.com/rust-lang/cargo/issues/1171
aptos-crypto = { git = "https://github.com/aptos-labs/aptos-core/", tag = "aptos-node-v1.9.1", optional = true }
aptos-types = { git = "https://github.com/aptos-labs/aptos-core/", tag = "aptos-node-v1.9.1", optional = true }


[dev-dependencies]
reqwest = { version = "0.11.23", features = ["blocking"] }

[features]
aptos = ["dep:aptos-crypto", "dep:aptos-types"]

[patch.crates-io]
merlin = { git = "https://github.com/aptos-labs/merlin" }
x25519-dalek = { git = "https://github.com/aptos-labs/x25519-dalek", branch = "zeroize_v1" }
