# Creates a PR benchmark comment with a comparison to the base branch
name: Benchmark pull requests
on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Comparative PR benchmark comment
    uses: lurk-lab/ci-workflows/.github/workflows/bench-pr-comment.yml@main
    with:
      default-benches: "proof"
