name: Gnark

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
    paths:
      - 'near/**'

defaults:
  run:
    working-directory: ./near/gnark-plonky2-verifier

jobs:
  check:

    name: gnark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...
