on:
  schedule:
  - cron:  "0 */2 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    name: Sync changes from upstream Lurk-lab repo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://x-access-token:${{ secrets.LURK_LAB_READ_TOKEN }}@github.com/lurk-lab/aptos-lc.git"
        source_branch: "main"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
